# Generated by Django 5.0.6 on 2024-07-02 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/advertising/image')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/advertising/video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('telegram_id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=40, null=True)),
                ('lastname', models.CharField(blank=True, max_length=40, null=True)),
                ('language', models.CharField(blank=True, default='uz', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideosRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('video_file', models.FileField(blank=True, null=True, upload_to='media/videos/')),
                ('music', models.FileField(blank=True, null=True, upload_to='media/music/')),
                ('image', models.FileField(blank=True, null=True, upload_to='media/image/')),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user_tg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tg_id', to='telesave.users')),
            ],
        ),
    ]
